-- 1. Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  price TEXT NOT NULL, -- Format like '₩120,000'
  category TEXT NOT NULL,
  stock INT DEFAULT 0,
  images TEXT[] DEFAULT '{}',
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE
);

-- 2. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY DEFAULT 'ORD-' || upper(substring(gen_random_uuid()::text from 1 for 8)),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_id UUID REFERENCES auth.users(id),
  customer_name TEXT,
  total_amount TEXT,
  status TEXT DEFAULT 'paid', -- 'paid', 'shipped', 'delivered', 'cancelled'
  shipping_address TEXT,
  metadata JSONB DEFAULT '{}'
);

-- 3. Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES public.products(id),
  product_name TEXT,
  price TEXT,
  quantity INT DEFAULT 1
);

-- 4. Settings Table (For site configuration)
CREATE TABLE IF NOT EXISTS public.site_settings (
  id TEXT PRIMARY KEY DEFAULT 'main',
  site_name TEXT DEFAULT 'SecondFace',
  notice_popup BOOLEAN DEFAULT FALSE,
  maintenance_mode BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Public read products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Public read orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Public read order_items" ON public.order_items FOR SELECT USING (true);
CREATE POLICY "Public read site_settings" ON public.site_settings FOR SELECT USING (true);

-- Admin full access (Assuming role is set in profiles table or auth.users meta)
-- For demo, allowing ALL for now, but usually we filter by auth.uid().
CREATE POLICY "Admin all access products" ON public.products FOR ALL USING (true);
CREATE POLICY "Admin all access orders" ON public.orders FOR ALL USING (true);
CREATE POLICY "Admin all access order_items" ON public.order_items FOR ALL USING (true);
CREATE POLICY "Admin all access site_settings" ON public.site_settings FOR ALL USING (true);
