-- Create Notices Table
CREATE TABLE IF NOT EXISTS notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  content TEXT,
  category TEXT DEFAULT 'NOTICE', -- 'NOTICE', 'EVENT', 'NEWS'
  read_count INT DEFAULT 0,
  author_id UUID REFERENCES auth.users(id)
);

-- Create Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  content TEXT,
  author TEXT, -- Can be display name
  author_id UUID REFERENCES auth.users(id),
  image_url TEXT,
  likes INT DEFAULT 0,
  comments INT DEFAULT 0
);

-- Create QnA Table
CREATE TABLE IF NOT EXISTS qna (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  content TEXT,
  author TEXT,
  author_id UUID REFERENCES auth.users(id),
  status TEXT DEFAULT 'Waiting', -- 'Waiting', 'Answered'
  answer TEXT,
  is_secret BOOLEAN DEFAULT FALSE,
  password TEXT -- Simple password for guest posts if needed, or just link to auth
);

-- Enable Row Level Security (RLS) - Optional for now but good practice
-- ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE qna ENABLE ROW LEVEL SECURITY;

-- Policies (simplified public access for demo)
-- CREATE POLICY "Public notices are viewable by everyone" ON notices FOR SELECT USING (true);
-- CREATE POLICY "Public reviews are viewable by everyone" ON reviews FOR SELECT USING (true);
-- CREATE POLICY "Public qna are viewable by everyone" ON qna FOR SELECT USING (true);

-- 4. Brand Page Images
CREATE TABLE IF NOT EXISTS brand_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  image_url TEXT NOT NULL,
  display_order INT DEFAULT 0
);

ALTER TABLE brand_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public brand_images access" ON brand_images FOR ALL USING (true) WITH CHECK (true);
