-- 1. Users Table (Ensure RLS is enabled if needed, but keeping simple for now)
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  profile_image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Products Table
create table if not exists public.products (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  price text not null,
  category text check (category in ('sunglasses', 'frames', 'goggles')),
  description text,
  images text[],
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Orders Table
create table if not exists public.orders (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users(id),
  total_amount integer,
  status text check (status in ('pending', 'paid', 'failed', 'cancelled', 'shipped', 'delivered')),
  payment_id text, -- PortOne payment_id (imp_uid)
  merchant_uid text unique, -- Unique order number generated by us
  payment_method text, -- card, vbank, kakaopay, etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Order Items Table
create table if not exists public.order_items (
  id uuid default uuid_generate_v4() primary key,
  order_id uuid references public.orders(id),
  product_id uuid references public.products(id),
  quantity integer default 1
);

-- 5. Posts Table (Community)
create table if not exists public.posts (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users(id),
  title text not null,
  content text,
  type text check (type in ('review', 'qna')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Insert Mock Data into Products (Optional, for initial testing)
insert into public.products (name, price, category, description, images, stock)
values 
('Zero-G Alpha', '₩280,000', 'sunglasses', 'Ultimate lightweight experience.', ARRAY['/hero-glasses.png'], 100),
('Nebula X', '₩320,000', 'sunglasses', 'Inspired by cosmic dust.', ARRAY['/hero-glasses.png'], 50),
('Eclipse Bold', '₩350,000', 'frames', 'Bold frames for bold vision.', ARRAY['/hero-glasses.png'], 30);
